#!/usr/bin/env python3
"""
SupportGraph AI — Unified LLM Provider Verification Script

Tests connectivity, model accessibility, and completion capability for configured
LLM providers (Groq or Ollama).

Usage:
    # Verify default provider from .env / settings
    python -m backend.scripts.verify_llm

    # Verify Groq specifically
    python -m backend.scripts.verify_llm --provider groq

    # Verify Ollama specifically
    python -m backend.scripts.verify_llm --provider ollama
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Add repo root to sys.path
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

try:
    from app.core.config import settings
    from app.core.llm_factory import get_llm_client
    from app.core.logging import configure_logging
except ModuleNotFoundError:
    from backend.app.core.config import settings  # type: ignore[no-redef]
    from backend.app.core.llm_factory import get_llm_client  # type: ignore[no-redef]
    from backend.app.core.logging import configure_logging  # type: ignore[no-redef]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Verify LLM Provider Connectivity and Model Access"
    )
    parser.add_argument(
        "--provider",
        type=str,
        choices=["groq", "ollama"],
        default=None,
        help=f"LLM provider to verify (default: active provider '{settings.llm_provider}')",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Optional model override for testing",
    )
    return parser.parse_args()


def main() -> int:
    configure_logging(log_level="INFO")
    args = parse_args()

    provider = args.provider or settings.llm_provider
    print("=" * 60)
    print(f"SupportGraph AI — LLM Provider Verification: {provider.upper()}")
    print("=" * 60)

    try:
        client = get_llm_client(provider=provider, model=args.model)
    except Exception as exc:
        print(f"[FAIL] Could not initialize LLM client for provider '{provider}': {exc}")
        return 1

    print(f"Provider: {client.provider}")
    print(f"Model:    {client.model}")

    # 1. Verify Model Access
    print("\n[Step 1/2] Verifying model accessibility...")
    is_valid, available_models, err_msg = client.verify_access()

    if not is_valid:
        print(f"[FAIL] Model verification failed: {err_msg}")
        if available_models:
            print(f"       Available models on {provider} ({len(available_models)}):")
            for m in available_models:
                print(f"         - {m}")
        return 1

    print(f"[PASS] Model '{client.model}' is confirmed accessible.")
    print(f"       Total models available on {provider}: {len(available_models)}")

    # 2. Test Minimal Completion
    print("\n[Step 2/2] Testing minimal completion...")
    test_messages = [
        {"role": "user", "content": "Respond with the word: PING"}
    ]
    try:
        response = client.chat_completion(
            messages=test_messages,
            temperature=0.0,
            max_tokens=64,
        )
        content_preview = response.content.strip().replace("\n", " ")[:60]
        print(f"[PASS] Completion succeeded! Response: \"{content_preview}\"")
        print(f"       Generated by model: {response.model_name}")
        if response.prompt_tokens or response.completion_tokens:
            print(f"       Tokens: prompt={response.prompt_tokens}, completion={response.completion_tokens}")
    except Exception as exc:
        print(f"[FAIL] Completion failed: {exc}")
        return 1

    print("\n" + "=" * 60)
    print(f"[SUCCESS] {provider.upper()} provider is fully operational!")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    sys.exit(main())
